USGS-R/training-curriculum

content/Outline.Rmd, content/Outline.md
Not sure why:
https://gohugo.io/extras/crossreferences/
=> Can't seem to get this to work.

themes/hugo_theme_robust/layouts/_default/single.html, themes/hugo_theme_robust/static/css/styles.css
@ldecicco-USGS This adds the previous and next buttons onto the top of the blog pages just like the bottom of it. Added a CSS arrow in each button as requested. This is all revolving the single.html blog posts, which seems to be all what the blogs are using, but if you someday change your mind and not use the single.html the buttons will not keep all the code I gave it. Just a heads up!
=> previous next changes

themes/hugo_theme_robust/layouts/index.html
Allows the blog teases all to be the same size instead of everyone after 4 being smaller
=> blogs all the same size

themes/hugo_theme_robust/layouts/partials/header_after.html, themes/hugo_theme_robust/static/css/styles.css
@lindsaycarr And for the hugo blog
=> training drop down for intro hugo

themes/hugo_theme_robust/static/css/styles.css
@ldecicco-USGS Did you want the squares to be smaller too?
=> code styling for intro

themes/hugo_theme_robust/static/css/styles.css
Made the intro notecards the same size as the owi blog notecards
=> Notecards size

content/course-specific-material/introR-NatGW-Aug16.Rmd, content/course-specific-material/introR-NatGW-Aug16.md
the schedule table is messed up, but I can't figure out a better way to format it
=> new markdown file added for GW workshop

themes/hugo_theme_robust/layouts/partials/header_after.html
@lindsaycarr look about right?
=> new updated links

themes/hugo_theme_robust/layouts/partials/header_after.html
@lindsaycarr Can you test to see if this works?
=> base origin url

content/course-specific-material/introR-NatGW-Aug16.Rmd, content/course-specific-material/introR-NatGW-Aug16.md, content/course-specific-material/introR-NatGW-Aug29/gw_analysis.Rmd, content/course-specific-material/introR-SWFLWMD-Sep16.Rmd, content/course-specific-material/introR-SWFLWMD-Sep16.md, content/intro-curriculum/Before-The-Workshop.Rmd, content/intro-curriculum/Before-The-Workshop.md, content/intro-curriculum/data.Rmd, content/intro-curriculum/data.md, content/intro-curriculum/data/create_df.R
- Nat GW .md updated to include this page on the collapsible menu
- data files linked in Nat GW markdown
- disclaimer in data.Rmd about how NWIS data is manipulated to create the datasets used here
- script for creating those datasets has been added from gsIntroR
- Nat GW analysis markdown updated to use readxl
=> Nat GW additions + disclaimer for data used in curriculum

themes/hugo_theme_robust/layouts/partials/header_after.html
=> remove double slash in URLs

content/course-specific-material/introR-LMGWSCAR-Oct16.Rmd, content/course-specific-material/introR-LMGWSCAR-Oct16.md
@eread-usgs if you need to make edits to their course page (add material, links, etc), change this .Rmd file and then knit. Make sure the knitted .Md file header is the same as it is here rather than the default after knitting.
```
---
date: 2016-10-25
slug: introR-LMGWSCAR-Oct16
title: LMGWSC - Arkansas
menu: 
main:
parent: Course Specific Material
weight: 1
---
```
=> LMGWSC AR course page

content/course-specific-material/introR-LMGWSCTN-Oct16.Rmd, content/course-specific-material/introR-LMGWSCTN-Oct16.md, content/intro-curriculum/A_Introduction.Rmd, content/intro-curriculum/A_Introduction.md, content/intro-curriculum/B_Get.Rmd, content/intro-curriculum/B_Get.md, content/intro-curriculum/C_Clean.Rmd, content/intro-curriculum/C_Clean.md, content/intro-curriculum/D_Explore.Rmd, content/intro-curriculum/D_Explore.md, content/intro-curriculum/E_Analyze.Rmd, content/intro-curriculum/E_Analyze.md, content/intro-curriculum/F_Analyze.Rmd, content/intro-curriculum/F_Analyze.md, content/intro-curriculum/G_Visualize.Rmd, content/intro-curriculum/G_Visualize.md, content/intro-curriculum/H_Visualize.Rmd, content/intro-curriculum/H_Visualize.md, content/intro-curriculum/I_Repeat-Reproduce.Rmd, content/intro-curriculum/I_Repeat-Reproduce.md, content/intro-curriculum/J_Parting-Thoughts-and-Extra-Materials.Rmd, content/intro-curriculum/J_Parting-Thoughts-and-Extra-Materials.md
Had to order the modules using dates in a reverse order (9999-01-10 appears before 9999-01-01)
=> shiny example zipfile + fake dates to order modules

content/intro-curriculum/Before-The-Workshop.Rmd, content/intro-curriculum/Before-The-Workshop.md
@jiwalker-usgs should we actually do this?
=> remove smwr and gsIntroR package installs + add geoknife

content/course-specific-material/introR-SAWSC-Feb17.Rmd, content/course-specific-material/introR-SAWSC-Feb17.md
=> smwrQW and rloadest blurbs for SA WSC

content/usgs-packages/Getting_Started.Rmd, content/usgs-packages/Getting_Started.md, content/usgs-packages/dataRetrieval_Discovery.Rmd, content/usgs-packages/dataRetrieval_Discovery.md, content/usgs-packages/dataRetrieval_Intro.Rmd, content/usgs-packages/dataRetrieval_Intro.md
Merging myself because I just added dates and need to get the build working.
=> need dates or Jenkins build fails

content/course-specific-material/introR-SAWSC-Feb17.Rmd, content/course-specific-material/introR-SAWSC-Feb17.md
merging myself -- minor updates needed for class tomorrow
=> update Wednesday schedule + zip file link

content/intro-curriculum/C_Clean.Rmd, content/intro-curriculum/C_Clean.md, content/intro-curriculum/D_Explore.Rmd, content/intro-curriculum/D_Explore.md, content/intro-curriculum/G_Visualize.Rmd, content/intro-curriculum/G_Visualize.md
See #140 (bonus! also fixing #93)
=> updates to curriculum from SA WSC training

content/intro-curriculum/B_Get.Rmd, content/intro-curriculum/B_Get.md
Thoughts on doing it this way?
=> Try to explain colClasses a bit more clearly

content/usgs-packages/geoknife_Execute.Rmd, content/usgs-packages/geoknife_Execute.md
Addressing #109 
@jiwalker-usgs please review when you can. Same as before, feel free to merge and check out on dev if you'd rather look at it that way.
=> geoknife - construct calls

content/course-specific-material/introR-NYCDEP-Apr17.Rmd, content/course-specific-material/introR-NYCDEP-Apr17.md
=> nyc dep scripts

content/r-package-dev/Documentation.Rmd, content/r-package-dev/Documentation.md, content/r-package-dev/Getting_Started.Rmd, content/r-package-dev/Getting_Started.md
Here is the start to the page about documentation (see #156). So far, I have introduced the topic and described vignettes. I know that I am missing how to make the vignettes produce a PDF and HTML, but I'm not entirely sure myself. 
I don't feel the need to add the help files section before merging. So a review, then edits on my part will be good to complete this PR.
=> Rpkg -- documentation (vignettes)

content/r-package-dev/Version_Control.Rmd, content/r-package-dev/Version_Control.md
=> version control image paths working now

content/usgs-packages/arg_table_functions.R, content/usgs-packages/dataRetrieval_readNWIS.Rmd, content/usgs-packages/dataRetrieval_readNWIS.md, content/usgs-packages/dataRetrieval_readWQP.Rmd, content/usgs-packages/dataRetrieval_readWQP.md
Two things happened with this PR:
1) made the way we create argument tables a little cleaner by pulling those functions into their own script, `arg_table_functions.R` and updated the readNWIS functions page to reflect this
2) added the readWQP functions page, per #106 
@ldecicco-USGS please review. I'm hoping to fix things you bring up next week
=> readWQP functions page

content/r-package-dev/Defensive_Programming.Rmd, content/r-package-dev/Defensive_Programming.md
struggling with that link to the Retries subsection
=> Pkg dev - defensive programming - less easy edit

content/r-package-dev/Maintenance.Rmd, content/r-package-dev/Maintenance.md
Mostly outline only, but I think this is a decent start for the scope of this module. 
Anything I left out that should be in? Anything I included that probably isn't worth the time/space?
I will be adding prose/examples in the future.
=> Outline for Maintenance

content/r-package-dev/Documentation.Rmd, content/r-package-dev/Documentation.md
=> two additions to documentation

content/r-package-dev/Documentation.Rmd, content/r-package-dev/Documentation.md, content/r-package-dev/Getting_Started.Rmd, content/r-package-dev/Getting_Started.md, content/r-package-dev/Version_Control.Rmd, content/r-package-dev/Version_Control.md
completing #159 & fixing in-line links
=> populate Getting Started for pkg dev workshop

content/r-package-dev/Defensive_Programming.md, content/r-package-dev/Documentation.md, content/r-package-dev/Getting_Started.md, content/r-package-dev/Maintenance.md, content/r-package-dev/Package_Mechanics.md, content/r-package-dev/Package_Thoughts.md, content/r-package-dev/Version_Control.md, content/r-package-dev/Writing_Tests.md, content/r-package-dev/debugging.md
@ldecicco-USGS please merge if we're ready to move this out! (I'll deploy jenkins prod)
=> remove draft tags

content/r-package-dev/Package_Mechanics.Rmd, content/r-package-dev/Package_Mechanics.md
Not going to push to prod - I think this small of a change isn't worth it.
=> tiny spelling mistake

content/r-package-dev/debugging.Rmd, content/r-package-dev/debugging.md
=> don't need to install with fork

content/usgs-packages/geoknife_Discovery.md
=> re-knit to get GDP changes to URLs

content/usgs-packages/geoknife_Discovery.Rmd, content/usgs-packages/geoknife_Discovery.md, content/usgs-packages/geoknife_Execute.Rmd, content/usgs-packages/geoknife_Execute.md, content/usgs-packages/sbtools_Intro.Rmd, content/usgs-packages/sbtools_Intro.md
Small changes that needed to be made to the geoknife lessons. Found these when working on #110
=> geoknife lessons small edits + sbtools intro

content/usgs-packages/Application_Intro.Rmd, content/usgs-packages/Application_Intro.md
=> start to application module intro

content/usgs-packages/sbtools_sbitem.Rmd, content/usgs-packages/sbtools_sbitem.md
@aappling-usgs let me know what you think!
=> "what's an sbitem?" lesson

content/usgs-packages/Getting_Started_USGS.Rmd, content/usgs-packages/Getting_Started_USGS.md
=> add better setup instructions

content/usgs-packages/geoknife_Assessment.Rmd, content/usgs-packages/geoknife_Assessment.md
Fixes #127. Still can't figure out why the last exercise is giving a data point on 2007-07-03 instead of 2007-07-04. @jiwalker-usgs please review when you get a chance.
=> exercises for geoknife

content/R_Software_Setup.Rmd, content/R_Software_Setup.md
=> order side menu: add weight to installr page

content/R_Software_Setup.Rmd, content/R_Software_Setup.md
Self-merging because this was supposed to be out on prod already.
=> install instructions not draft

content/usgs-packages/sbtools_Assessment.Rmd, content/usgs-packages/sbtools_Assessment.md, content/usgs-packages/sbtools_Discovery.Rmd, content/usgs-packages/sbtools_Discovery.md
=> sbtools assessment

content/usgs-packages/dataRetrieval_Intro.Rmd, content/usgs-packages/dataRetrieval_Intro.md, themes/hugo_theme_robust/layouts/section/usgs-packages.html
Fixes #294 & allowed all tiles to show up on USGS Packages course index page
=> WQP paper link + index page formatting

content/usgs-packages/Closing_Remarks_USGS.Rmd, content/usgs-packages/Closing_Remarks_USGS.md, content/usgs-packages/Getting_Started_USGS.Rmd, content/usgs-packages/Getting_Started_USGS.md, content/usgs-packages/Glossary.Rmd, content/usgs-packages/Glossary.md
=> Closing remarks for usgs-packages curriculum

content/usgs-packages/Application_Intro.Rmd, content/usgs-packages/Application_Intro.md
forgot that this was part of #289
=> remove 3rd unrelated goal for application

content/course-specific-material/introR-Reston-Aug17.Rmd, content/course-specific-material/introR-Reston-Aug17.md
=> zip file link

themes/hugo_theme_robust/static/css/styles.css
Made the light blue a dark blue and pretty sure the class with all the orange as well and made it black.
=> more color changes

content/usgs-packages/Getting_Started_USGS.Rmd, content/usgs-packages/Getting_Started_USGS.md
=> add Sam's time estimates

content/usgs-packages/geoknife_Execute.Rmd, content/usgs-packages/geoknife_Execute.md
Update based on https://github.com/USGS-CIDA/geo-data-portal/pull/274#pullrequestreview-61290511 and fixing #257
=> update language about email notifications

content/intro-curriculum/E_Analyze.Rmd, content/intro-curriculum/E_Analyze.md
Fixes #195. Not adding `select_if()` -- can't think of a great application for this and it seems like more of a power-user function.
=> qqplot + t-test w/ dates

themes/hugo_theme_robust/layouts/partials/header_after.html
Need to do this for https://github.com/USGS-R/usgs-r-website/blob/master/js/templates/nav.handlebars#L14-L33, but cannot get changes from upstream to work!!!! 
It would be nice to not merge this until that is complete (someone else might need to do it though).
=> drop down for usgs-packages material

content/course-specific-material/introR-Middleton-Oct17.Rmd, content/course-specific-material/introR-Middleton-Oct17.md
self-merging since it's just the schedule and contact info.
=> Middleton course page

content/course-specific-material/introR-CAWSC-Nov17.Rmd, content/course-specific-material/introR-CAWSC-Nov17.md, content/course-specific-material/introR-Middleton-Oct17.Rmd, content/course-specific-material/introR-Middleton-Oct17.md
self-merging b/c just added new course pages
=> middleton updated, added sacramento

content/course-specific-material/introR-CAWSC-Nov17.Rmd, content/course-specific-material/introR-CAWSC-Nov17.md
=> schedule update CAWSC

content/intro-curriculum/data/data_workflow.Rmd
First draft of the example Rmd we will walk through at the beginning of an introduction to R class. I intend for people to download this from the `data/` folder just like they grab csv files. Then we can open it, and be able to knit and walk through each line together.
I took the earthquake blog @ldecicco-USGS put together and adapted it so that it used stuff similar to what we will show in class and eliminated the spatial transform stuff (I just used `maps`). People can go to the real blog to see that, but I wanted to mimic more what we will cover in the class. If we decide to teach `ggplot2` in that particular class, we can just have people look at the plotting functions in the actual blog post.
For the figure, that last plot looks a little funky to me...did I do something wrong? It …
=> example Rmd to start class

content/course-specific-material/introR-CAWSC-Nov17.Rmd, content/course-specific-material/introR-CAWSC-Nov17.md, content/course-specific-material/introR-Middleton-Oct17.Rmd, content/course-specific-material/introR-Middleton-Oct17.md, content/intro-curriculum/data.Rmd, content/intro-curriculum/data.md, content/intro-curriculum/data/data_workflow.Rmd
needed for class tomorrow
merging
=> ggplot-ify the example workflow + link to example Rmd

content/course-specific-material/introR-NDWSC-Nov17.Rmd, content/course-specific-material/introR-NDWSC-Nov17.md
kept same schedule as Sacramento.
=> created Bismarck course site

content/intro-curriculum/C_Clean.Rmd, content/intro-curriculum/C_Clean.md
Just a tiny bit of merge language left from before we removed that I think
=> replace merge language with join in clean exercise

content/course-specific-material/introR-Denver-Apr19.Rmd, content/course-specific-material/introR-Denver-Apr19.md
It's Friday afternoon and I got lazy with catching mistakes.
=> make identifiers distinct

content/course-specific-material/introR-Harrisburg-Oct19.Rmd, content/course-specific-material/introR-Harrisburg-Oct19.md
=> pa wsc training info
